services:
  - type: web
    name: campus-bites-server
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node index.js
    rootDir: campus-bites/server
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: WHATSAPP_ENABLED
        value: "false"
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
